### ISSUE TITLE
Transpiling to Go from ilang: then running `go run filename.go` results in undefined: Stack

### ISSUE THREAD

**Issue by ghost** [Qlova/ilang#8]
I manage to run `it Arithmetic.it go` and it transpiles ok spitting out: 
    
    { Arithmetic.go, Arithmetic.u, ilang.u, stack.go } 

However whenever I run `go run Arithmetic.go` I get a series of undefined: Stack errors. Is this because the transpiled code is not automatically importing Stack.go?

**Comment by Splizard** [comment]
Yes,  there are two solutions to this,  you can change the file extension of Arithmetic.it to Arithmetic.i then when you run the "it" command it will automatically compile and run it for you. 
".i" is the official format. 

The other option is to use "go build" inside the folder because with Go, "go run" does not import  any other files. 

With both options you will need to ensure that you do not have multiple programs in the same folder,  eg. Don't have Arithmetic.i and SomethingElse.i

**Comment by Splizard** [comment]
Will close this issue, itool will now automatically compile and run the code for you in the language you pick.
